#!/bin/bash -x

# Target your bosh-lite UAA and get the 'admin' token
uaac target http://uaa.192.168.10.10.xip.io
uaac token client get admin -s c1oudc0w

# Add 'scim.write' if not already there and re-get token
uaac client update admin --authorities "`uaac client get admin | awk '/:/{e=0}/authorities:/{e=1;if(e==1){$1="";print}}'` scim.write"
uaac token client get admin -s c1oudc0w

# Delete previously created items
uaac client delete admin_ui_client
uaac group delete admin_ui.admin

# Create a new group and add the 'admin' user to it
uaac group add admin_ui.admin
uaac member add admin_ui.admin admin

# Create the new UAA admin_ui_client
uaac client add admin_ui_client --authorities cloud_controller.admin,cloud_controller.read,cloud_controller.write,openid,scim.read --authorized_grant_types authorization_code,client_credentials,refresh_token --autoapprove true --scope admin_ui.admin,admin_ui.user,openid -s c1oudc0w
